### ISSUE TITLE
Sup man

### ISSUE THREAD

**Issue by NewCreation4** [Natasquare/Natasquare#1]
ayo man reply to me

**Comment by Natasquare** [comment]
omg creation??!?!?

**Comment by NewCreation4** [comment]
yeah its me

**Comment by NewCreation4** [comment]
got banned both on discord and guilded and also my phone broke, now im on a new phone

**Comment by NewCreation4** [comment]
by the way i created a programming language

**Comment by NewCreation4** [comment]
fun fact: block strike has chat, Just go to the friends section and search "GalinhaSuprema1" and send a friend request to me

**Comment by NewCreation4** [comment]
then chat unlocreked

**Comment by Natasquare** [comment]
any chances that you get a new discord account?

**Comment by NewCreation4** [comment]
nope

**Comment by NewCreation4** [comment]
but i got guilded

**Comment by NewCreation4** [comment]
and block strike

**Comment by Natasquare** [comment]
me, who is inactive on both:

**Comment by NewCreation4** [comment]
h

**Comment by NewCreation4** [comment]
send friend request in block strike still

**Comment by NewCreation4** [comment]
hhhhhh

**Comment by Natasquare** [comment]
a

**Comment by NewCreation4** [comment]
did you send the friend request?

**Comment by NewCreation4** [comment]
changing your region to brazil may be need

**Comment by NewCreation4** [comment]
needed

**Comment by NewCreation4** [comment]
maybe

**Comment by NewCreation4** [comment]
or tell me ur block strike username

**Comment by NewCreation4** [comment]
so that i can send friend request

**Comment by NewCreation4** [comment]
hey, send me friend request on guilded imma get my tag and stuff so that you can friend me

**Comment by NewCreation4** [comment]
my name is Honey Bee

**Comment by NewCreation4** [comment]
sent you friend request

**Comment by NewCreation4** [comment]
HEY
